### ISSUE TITLE
BleCharacteristicNotFoundException after disabling/re-enabling Bluetooth

### ISSUE THREAD

**Issue by cpboyd** [Polidea/RxAndroidBle#121]
### Summary
I've noticed the BleCharacteristicNotFoundException occurring occasionally after the app is backgrounded or seemingly random times.

I've been able to reproduce this consistently by disabling Bluetooth (while connected) and then re-enabling it and connecting again.

Simply disconnecting and reconnecting doesn't seem to have the same issue.

This may be due to my limited understanding of Rx, but I can't seem to determine why the error is getting thrown.  All old subscriptions should be unsubscribed.

#### Error
```
BleCharacteristicNotFoundException{charactersisticUUID=09b0d0a6-f374-4051-a819-67c235f31438}
  at com.polidea.rxandroidble.RxBleDeviceServices.getCharacteristic(RxBleDeviceServices.java:63)
  at com.polidea.rxandroidble.internal.connection.RxBleConnectionImpl.lambda$getCharacteristic$53(RxBleConnectionImpl.java:126)
  at com.polidea.rxandroidble.internal.connection.RxBleConnectionImpl$$Lambda$1.call(Unknown Source)
  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
  at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
  at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:403)
  at rx.internal.operators.CachedObservable$CacheState.dispatch(CachedObservable.java:220)
  at rx.internal.operators.CachedObservable$CacheState.onNext(CachedObservable.java:191)
  at rx.internal.operators.CachedObservable$CacheState$1.onNext(CachedObservable.java:171)
  at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
  at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
  at rx.subjects.ReplaySubject$ReplayUnboundedBuffer.drain(ReplaySubject.java:644)
  at rx.subjects.ReplaySubject$ReplayState.onNext(ReplaySubject.java:457)
  at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:242)
  at com.polidea.rxandroidble.internal.RxBleRadioOperation.onNext(RxBleRadioOperation.java:86)
  at com.polidea.rxandroidble.internal.RxBleRadioOperation$1.onNext(RxBleRadioOperation.java:75)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
  at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
  at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
  at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
  at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onNext(OperatorTimeoutBase.java:131)
  at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
  at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
  at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.setProducer(OperatorTimeoutBase.java:115)
  at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
  at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
  at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
  at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
  at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
  at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
  at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
  at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
  at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$1$$Lambda$4.call(Unknown Source)
  at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
```

#### Preconditions
My setup is as follows:
(subList is a SubscriptionList that gets unsubscribed before this connect/reconnect)
```java
private PublishSubject<byte[]> inputSubject = PublishSubject.create();
private ResponseSubject outputSubject = ResponseSubject.create();

...

Observable<RxBleConnection> connectionObservable = bleClient.getBleDevice(macAddress).establishConnection(context, true);
if (subList != null)
    subList.unsubscribe();
subList = new SubscriptionList();
Subscription raw = connectionObservable
    .flatMap(
            rxBleConnection -> {
                Log.d(TAG, "Test...");
                rxBleConnection.writeCharacteristic(writeUuid, "?test".getBytes()).first().subscribe((bytes) -> Log.d(TAG, "Wrote test"), (tr) -> Log.d(TAG, "RxTest", tr));
                // connection is established and notification prepared
                subList.add(inputSubject.onBackpressureBuffer().flatMap(bytes -> {
                    Log.d(TAG, "Writing " + bytes.length + " bytes");
                    return rxBleConnection.writeCharacteristic(writeUuid, bytes);
                }).subscribe());
                return getNotif(rxBleConnection, notificationUuid, withAck);
            })
    .flatMap(observable -> observable)
    .doOnTerminate(() -> subList.unsubscribe())
    .subscribe(response -> { }, throwable -> outputSubject.onError(throwable));
subList.add(raw);
```

Note: The "test" write does not throw an error.

#### Steps to reproduce actual result
1.  Connect to device.
2.  Send/receive data.
3.  Disable Bluetooth from Android system menu.
4.  Re-enable and re-connect.
5. Attempting to write new data will result in the BleCharacteristicNotFoundException, but the data actually gets written (and I see the proper response come back from the device.)

#### Actual result
Error is thrown, but characteristic seems to be written.
#### Expected result
Error should not be thrown.

**Comment by dariuszseweryn** [comment]
Hello,
I am trying to reason about your code but it is hard as I do not see what exactly is the `connectionObservable` in your case. There is also no context about when your setup is run. When does your `inputSubject` emit? Can you confirm that the service discovery on a particular connection worked properly? (I have seen situations that the Android indicated that discovery ended but an empty list of services was returned) Your device, OS version?
Btw. it would be better to call `subList.unsubscribe();` in `.onTerminate()` of your `raw` `Subscription`

**Comment by cpboyd** [comment]
@dariuszseweryn 

I've updated the code in the original post.

`connectionObservable` is an `Observable<RxBleConnection>` created by calling `bleClient.getBleDevice(macAddress).establishConnection(context, true)`
I use `inputSubject` is simply a `PublishSubject<byte[]>` and I use it with the following function:

```java
public Observable<String> sendCmd(String data) {
    Log.d(TAG, "Writing data: " + data);
    inputSubject.onNext(data.getBytes());
    return outputSubject.filter(s -> {
        // Allow for potentially corrupted JSON:
        return s.startsWith("{\"CMD\":\"" + data + '"');
    }).first();
}
```

`outputSubject` is a custom `Subject` that reassembles the individual packets into a full response.

**Comment by dariuszseweryn** [comment]
But when your code from the first post is executed? It still lacks the context (state).
Point is - it looks like you have some state in your code that is wrong after turning the bluetooth off / on. I am judging this because when you say that you reinitialize everything from scratch the problem is gone and even with the exception being emitted you say that the peripheral receives the data.
I think I was not experiencing this issue when turning off / on the adapter. Will double check on Monday.

**Comment by cpboyd** [comment]
This was in a singleton that's passed the context but only initializes the RxBleClient once.

Ultimately, I found that I can re-initialize everything EXCEPT the `RxBleClient` and `RxBleDevice` and it seems to get rid of the error, so I don't think there's an issue with the library.

**Comment by dariuszseweryn** [comment]
Glad to hear that you have solved your problem. Thing is that everything that is created in a context of a specific connection should be only used within the context. I will think of how to inform about it clearly.
