### ISSUE TITLE
Fix library behaviour on environments where BluetoothAdapter is unavailable

### ISSUE THREAD

**Issue by StanislavChumarin** [Polidea/RxAndroidBle#158]
### Application crashes on emulator

<br />

#### Steps to reproduce actual result

1. Just try to run RxBleClient.create(context) on emulator or device without bluetooth
2.
3.

#### Actual result
```
java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
                                                                 at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
                                                                 at com.polidea.rxandroidble.ClientComponent_ClientModule_ProvideBlutetoothAdapterFactory.get(ClientComponent_ClientModule_ProvideBlutetoothAdapterFactory.java:20)
                                                                 at com.polidea.rxandroidble.ClientComponent_ClientModule_ProvideBlutetoothAdapterFactory.get(ClientComponent_ClientModule_ProvideBlutetoothAdapterFactory.java:8)
                                                                 at com.polidea.rxandroidble.internal.util.RxBleAdapterWrapper_Factory.get(RxBleAdapterWrapper_Factory.java:18)
                                                                 at com.polidea.rxandroidble.internal.util.RxBleAdapterWrapper_Factory.get(RxBleAdapterWrapper_Factory.java:8)
                                                                 at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:67)
                                                                 at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:16)
                                                                 at com.polidea.rxandroidble.ClientComponent_ClientModule_ProvideRxBleClientFactory.get(ClientComponent_ClientModule_ProvideRxBleClientFactory.java:25)
                                                                 at com.polidea.rxandroidble.ClientComponent_ClientModule_ProvideRxBleClientFactory.get(ClientComponent_ClientModule_ProvideRxBleClientFactory.java:8)
                                                                 at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                 at com.polidea.rxandroidble.DaggerClientComponent.rxBleClient(DaggerClientComponent.java:271)
                                                                 at com.polidea.rxandroidble.RxBleClient.create(RxBleClient.java:27)
```
<br />
#### Expected result
Just return NULL or empty stub implementation
<br />

**Comment by dariuszseweryn** [comment]
Hello @StanislavChumarin 
This issue should be fixed in the `1.3.0-SNAPSHOT` release.
Best Regards.
