### ISSUE TITLE
Untraceable, seemingly random crashes in RxBleScan

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#190]
### Summary
Sometimes, but not always, the app crashes after a scan
<br />
#### Preconditions
Scan for BLE devices
<br />
#### Steps to reproduce actual result
1. Start a scan
2. Scan finishes
3. Long and complex stack trace
#### Actual result
Crash
<br />
#### Expected result
No crash
<br />

I have been chasing this problem for weeks, and thought I had fixed it more than once. At first I thought it was the `.observeOn( AndroidSchedulers.mainThread())`, so I removed that, and it worked for a while. Then I thought maybe it was the `.take()` operators, so I removed those. Again, it seemed to work. I have now removed everything that isn't essential, and it's still blowing up. 

The last item in the stack trace "caused by" chain is this: 
`Caused by: java.lang.ClassCastException: io.aeroscope.aeroscope.AeroscopeBluetoothService cannot be cast to io.aeroscope.aeroscope.AeroscopeDisplay`
Maybe that is a clue. The above code resides in a Bound Service called AeroscopeBluetoothService, and is called by the Activity AeroscopeDisplay. The crash seems to have something to do with propagating an error; could that somehow cause the ClassCastException? 
And is there a chance that switching to the newer API 21 scanning API may help this? I'm getting desperate. 

Code: 
```
public void scanForAeroscopes( int numberToFind, long secondsToScan ) {  
        Log.d( LOG_TAG, "Entered new scanForAeroscopes()" );
        rxBleDeviceVector.clear( );
        asDeviceVector.clear( );
        nowScanning.set( true );                             // set "scan active" flag (synchronized)
        errorScanning.set( false );                          // clear the "scan error" flag
        scanSubscription = asBleClient
                .scanBleDevices( asServiceIdArray )          // argument must be an array, apparently
                //.take( numberToFind )                                // removed
                //.take( secondsToScan, TimeUnit.SECONDS )   // removed
                //.observeOn( AndroidSchedulers.mainThread() ) // removed
                .subscribe(
                        this::addRxBleScanResult, 
                        this::handleRxBleScanError,    
                        this::completeRxBleScan              // (was being called when .take() fired)
                );
    }

    public void scanForAeroscopes( ) {  //  no-arg overload
        scanForAeroscopes( MAX_AEROSCOPES, SCAN_TIME ); 
    }

    private void addRxBleScanResult( RxBleScanResult scanResult ) {
        RxBleDevice device = scanResult.getBleDevice();
        Log.d( LOG_TAG, "addRxBleScanResult about to call addRxBleDevice with device " + device.toString() );
        addRxBleDevice( device );
        completeRxBleScan();  // (have to fake a completion because the now-removed .take() was only thing causing scan to complete)
    }

    private void handleRxBleScanError( Throwable scanError ) {
        nowScanning.set( false );  
        errorScanning.set( true ); 
        Log.d( LOG_TAG, "scanSubscription onError() received: " + scanError.getMessage(), scanError );
    }

    private void completeRxBleScan() {   
        Log.d( LOG_TAG , "completeRxBleScan was called by scanSubscription; unsubscribing..." );
        scanSubscription.unsubscribe();
        nowScanning.set( false );  
        errorScanning.set( false ); 
        // Broadcast the results back to MainActivity
        Intent scanIntent = new Intent( "scanResults" );
        scanIntent.putExtra( "io.aeroscope.aeroscope.DeviceVector", asDeviceVector ); 
        LocalBroadcastManager.getInstance( getApplicationContext() ).sendBroadcast( scanIntent ); 
        Log.d( LOG_TAG, "scanSubscription onCompleted() broadcast asDeviceVector to MainActivity" );
    }

    // method to stop a device scan; NOTE use this instead of a simple unsubscribe()
    public synchronized void stopScanning() {
        scanSubscription.unsubscribe();
        nowScanning.set( false );
        Log.d( LOG_TAG, "stopScanning() has run" );
    }

```

Here is the log: 
```
05-08 11:15:09.938 30139-30139/io.aeroscope.aeroscope D/AeroscopeBluetoothServc: Entered new scanForAeroscopes()
05-08 11:15:09.956 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: isEnabled
05-08 11:15:09.977 30139-30139/io.aeroscope.aeroscope D/RxBle#Radio:   QUEUED RxBleRadioOperationScan(683083599)
05-08 11:15:09.978 30139-30166/io.aeroscope.aeroscope D/RxBle#Radio:  STARTED RxBleRadioOperationScan(683083599)
05-08 11:15:09.981 30139-30139/io.aeroscope.aeroscope D/MainActivity: Finished startScan()
05-08 11:15:10.002 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: startLeScan(): null
05-08 11:15:10.003 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: 972694662: getState(). Returning 12
05-08 11:15:10.008 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: 972694662: getState(). Returning 12
05-08 11:15:10.009 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: 972694662: getState(). Returning 12
05-08 11:15:10.015 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.033 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241517622537
05-08 11:15:10.039 30139-30157/io.aeroscope.aeroscope D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=1
05-08 11:15:10.043 30139-30139/io.aeroscope.aeroscope I/BluetoothLeScanner: startRegisteration: mLeScanClients={android.bluetooth.BluetoothAdapter$2@3e39ad74=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@32d0fae3}
05-08 11:15:10.044 30139-30166/io.aeroscope.aeroscope D/RxBle#Radio: FINISHED RxBleRadioOperationScan(683083599)
05-08 11:15:10.113 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.117 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241601033120
05-08 11:15:10.125 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.133 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241617736410
05-08 11:15:10.146 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.180 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241651118855
05-08 11:15:10.181 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.181 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241667816672
05-08 11:15:10.198 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.216 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241701154225
05-08 11:15:10.223 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.233 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241717858683
05-08 11:15:10.241 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.248 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241734532903
05-08 11:15:10.257 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.265 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241751203282
05-08 11:15:10.276 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.283 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241767957576
05-08 11:15:10.294 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.298 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241784647138
05-08 11:15:10.310 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.315 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241801342562
05-08 11:15:10.325 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 requestNextVsync
05-08 11:15:10.334 30139-30165/io.aeroscope.aeroscope D/OpenGLRenderer: DisplayEventReceiver 0xa3d23050 latestVsyncEvent 76241818019330
05-08 11:15:10.437 30139-30156/io.aeroscope.aeroscope D/BluetoothLeScanner: onScanResult() - ScanResult{mDevice=CC:C6:B5:9F:9A:F7, mScanRecord=ScanRecord [mAdvertiseFlags=6, mServiceUuids=[f9541234-91b3-bd9a-f077-80f2a6e57d00], mManufacturerSpecificData={}, mServiceData={}, mTxPowerLevel=-2147483648, mDeviceName=Jack's Aeroscope������], mRssi=-71, mTimestampNanos=76241918015619}
05-08 11:15:10.441 30139-30139/io.aeroscope.aeroscope D/BluetoothDevice: mAddress: CC:C6:B5:9F:9A:F7
05-08 11:15:10.460 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: stopLeScan()
05-08 11:15:10.460 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: 972694662: getState(). Returning 12
05-08 11:15:10.461 30139-30139/io.aeroscope.aeroscope D/BluetoothAdapter: 972694662: getState(). Returning 12
05-08 11:15:10.461 30139-30139/io.aeroscope.aeroscope I/BluetoothLeScanner: startRegisteration: mLeScanClients={android.bluetooth.BluetoothAdapter$2@3e39ad74=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@32d0fae3} ,callback=android.bluetooth.BluetoothAdapter$2@3e39ad74
05-08 11:15:10.472 30139-30139/io.aeroscope.aeroscope D/AndroidRuntime: Shutting down VM
05-08 11:15:10.480 30139-30139/io.aeroscope.aeroscope E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: io.aeroscope.aeroscope, PID: 30139
                                                                        rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
                                                                            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                            at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                                            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                            at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:585)
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:283)
                                                                            at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                                            at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
                                                                            at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
                                                                            at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                            at rx.subjects.ReplaySubject$ReplayUnboundedBuffer.drain(ReplaySubject.java:644)
                                                                            at rx.subjects.ReplaySubject$ReplayState.onNext(ReplaySubject.java:457)
                                                                            at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:242)
                                                                            at com.polidea.rxandroidble.internal.RxBleRadioOperation.onNext(RxBleRadioOperation.java:92)
                                                                            at com.polidea.rxandroidble.internal.operations.RxBleRadioOperationScan.access$000(RxBleRadioOperationScan.java:17)
                                                                            at com.polidea.rxandroidble.internal.operations.RxBleRadioOperationScan$1.onLeScan(RxBleRadioOperationScan.java:43)
                                                                            at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1725)
                                                                            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:337)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
                                                                         Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187) 
                                                                            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
                                                                            at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) 
                                                                            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) 
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235) 
                                                                            at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120) 
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:585) 
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:283) 
                                                                            at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) 
                                                                            at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395) 
                                                                            at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355) 
                                                                            at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846) 
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235) 
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235) 
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235) 
                                                                            at rx.subjects.ReplaySubject$ReplayUnboundedBuffer.drain(ReplaySubject.java:644) 
                                                                            at rx.subjects.ReplaySubject$ReplayState.onNext(ReplaySubject.java:457) 
                                                                            at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:242) 
                                                                            at com.polidea.rxandroidble.internal.RxBleRadioOperation.onNext(RxBleRadioOperation.java:92) 
                                                                            at com.polidea.rxandroidble.internal.operations.RxBleRadioOperationScan.access$000(RxBleRadioOperationScan.java:17) 
                                                                            at com.polidea.rxandroidble.internal.operations.RxBleRadioOperationScan$1.onLeScan(RxBleRadioOperationScan.java:43) 
                                                                            at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1725) 
                                                                            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:337) 
                                                                            at android.os.Handler.handleCallback(Handler.java:815) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                            at android.os.Looper.loop(Looper.java:194) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5576) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751) 
                                                                         Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                            at android.util.Log.getStackTraceString(Log.java:330)
                                                                            at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
                                                                            at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
                                                                            at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
                                                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                         Caused by: java.lang.ClassCastException: io.aeroscope.aeroscope.AeroscopeBluetoothService cannot be cast to io.aeroscope.aeroscope.AeroscopeDisplay
                                                                            at io.aeroscope.aeroscope.-$Lambda$12.$m$0(Unknown Source)
                                                                            at io.aeroscope.aeroscope.-$Lambda$12.call(Unknown Source)
                                                                            at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                            at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                                                                            at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:585)
                                                                            at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:283)
                                                                            at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                                            at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
                                                                        	at rx.intern
05-08 11:17:17.770 30139-30150/io.aeroscope.aeroscope W/art: Suspending all threads took: 8.263ms
05-08 11:18:41.585 30139-30157/io.aeroscope.aeroscope D/MessageLogger: >>> Entering MessageLogger.dump. to Dump MSG HISTORY <<<
05-08 11:18:41.603 30139-30157/io.aeroscope.aeroscope D/MessageLogger: MSG HISTORY IN MAIN THREAD:
                                                                       Current kernel time : 76453073ms
                                                                       Last record : Msg#:106 >>>>> Dispatching to Handler (android.os.Handler) {2c258b99} android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1@ddb3e5e: 0
                                                                       Last record dispatching elapsedTime:211160 ms/upTime:211160 ms
                                                                       Last record dispatching time : 2017-05-08 11:15:10.440
                                                                       Msg#:105 <<<<< Finished to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13 elapsedTime:1 ms/upTime:2 ms
                                                                       Msg#:104 >>>>> Dispatching to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13: 0 from 2017-05-08 11:15:10.382
                                                                       Msg#:103 <<<<< Finished to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13 elapsedTime:2 ms/upTime:3 ms
                                                                       Msg#:102 >>>>> Dispatching to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13: 0 from 2017-05-08 11:15:10.365
                                                                       Msg#:101 <<<<< Finished to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13 elapsedTime:2 ms/upTime:3 ms
                                                                       Msg#:100 >>>>> Dispatching to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13: 0 from 2017-05-08 11:15:10.349
                                                                       Msg#:99 <<<<< Finished to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13 elapsedTime:3 ms/upTime:3 ms
                                                                       Msg#:98 >>>>> Dispatching to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13: 0 from 2017-05-08 11:15:10.331
                                                                       Msg#:97 <<<<< Finished to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13 elapsedTime:1 ms/upTime:1 ms
                                                                       Msg#:96 >>>>> Dispatching to Handler (android.view.Choreographer$FrameHandler) {a12d602} android.view.Choreographer$FrameDisplayEventReceiver@ec5eb13: 0 from 2017-05-08 11:15:10.316
                                                                       ***Flushing, Current Size Is:2135,boolfalse***TAIL
```

**Comment by dariuszseweryn** [comment]
As it turned out - the cause was `jack` which was not regenerating lambdas as it should. Clean build solved the problem.

**Comment by RobLewis** [comment]
Just as an additional data point, I have now run several development versions of the app multiple times. As long as I Clean the project before each run, I don't have a problem. I'm still using Jack. The Clean operation is fairly quick, so it's not too burdensome.
