### ISSUE TITLE
Encountering MissingBackPressureException with lots of characteristic changes

### ISSUE THREAD

**Issue by pfives** [Polidea/RxAndroidBle#21]
First of all thank you for this library. You guys have done a seriously awesome job. 

Occasionally I am encountering a MissingBackPressureException when I create an observable that establishes a connection and listens for characteristic changes (`setupNotification(CHARACTERISITC)`)

In my use case there are lots of characteristic changes that we use to read data from the device but occasionally when there are more than normal it will crash with a MissingBackPressureException. 

Have you guys encountered this / known behavior? Is there a specific way you recommend dealing with this on the app side to avoid changes to the lib? Thanks again. 

```rx.exceptions.CompositeException: 4 exceptions occurred. 
at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:255)
at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:797)
at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:690)
at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:416)
at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:223)
at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$1$$Lambda$7.call(Unknown Source)
at rx.Observable$27.onNext(Observable.java:8571)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)```

**Comment by mzgreen** [comment]
This error means that your `Observable` emits items faster than you consume them. For now you can try to use one of the backpressure operators like `onBackpressureBuffer` and we'll check what we can do about it internally.

**Comment by dariuszseweryn** [comment]
@pfives - as @mzgreen has proposed - you should either use onBackpressureBuffer or any other operator that suits best your needs (checkout https://github.com/ReactiveX/RxJava/wiki/Backpressure ). If we would have implemented any specific handling of the backpressure in the library someone other's usecases would not be covered.
Have I answered your question?

**Comment by pfives** [comment]
@dariuszseweryn yes makes sense thank you. I have to dig into that a bit but seems pretty straightforward. Thanks for the help and the awesome lib!
