### ISSUE TITLE
BleDisconnectedException when to connect

### ISSUE THREAD

**Issue by Mike-bel** [Polidea/RxAndroidBle#286]
It is the LG mobile phone. Sometimes it can connects successfully, but sometimes failed, and this is the throwable info:

```
09-21 14:57:11.673 10959-14201/ble.ubike.com.ble_demo D/BluetoothManager: getConnectionState()
09-21 14:57:11.673 10959-14201/ble.ubike.com.ble_demo D/BluetoothManager: getConnectedDevices
09-21 14:57:11.676 10959-14201/ble.ubike.com.ble_demo D/BluetoothGatt: close()
09-21 14:57:11.677 10959-14201/ble.ubike.com.ble_demo D/BluetoothGatt: unregisterApp() - mClientIf=6
09-21 14:57:11.681 10959-14201/ble.ubike.com.ble_demo D/BluetoothGatt: connect() - device: C8:FD:19:94:FC:26, auto: false
09-21 14:57:11.681 10959-14201/ble.ubike.com.ble_demo D/BluetoothGatt: registerApp()
09-21 14:57:11.681 10959-14201/ble.ubike.com.ble_demo D/BluetoothGatt: registerApp() - UUID=28b57239-49e0-4a57-86f2-b6d9950b596d
09-21 14:57:11.682 10959-11094/ble.ubike.com.ble_demo D/BluetoothGatt: onClientRegistered() - status=0 clientIf=6
09-21 14:57:11.685 10959-11094/ble.ubike.com.ble_demo D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=6 device=C8:FD:19:94:FC:26
09-21 14:57:11.686 10959-10959/ble.ubike.com.ble_demo E/BleLib: BleDisconnectedException{bluetoothDeviceAddress='C8:FD:19:94:FC:26'}
                                                                    at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:76)
                                                                    at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:182)
                                                                    at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
                                                                    at android.os.Binder.execTransact(Binder.java:446)
```

Is this the mobile problem or api using problem, please?

Add one point: the other phones are normal.

**Comment by dariuszseweryn** [comment]
Hello @Mike-bel 
Please try to conform to the template that is given when creating an issue.
Without `btsnoop_hci.log` file I cannot tell anything 100% sure but most probably it is a mobile BLE stack problem.

**Comment by Mike-bel** [comment]
Thanks for your reply. @dariuszseweryn 
I have tried for more times on my LG phone, and still failed to connect.
But other phones are OK.
What is the `btsnoop_hci.log` file, Please?

**Comment by dariuszseweryn** [comment]
It is a file that contain low-level BT communication logs. You can find how to enable the log [here](https://blog.bluetooth.com/debugging-bluetooth-with-an-android-app). Please make sure that only one connection try is logged. Another file from another phone that is working ok would be good for comparison.

**Comment by Mike-bel** [comment]
[btsnoop_hci.zip](https://github.com/Polidea/RxAndroidBle/files/1324778/btsnoop_hci.zip)

Hello @dariuszseweryn 

I've saved two log files. `btsnoop_hci.cfa` is the successful connection on another phone, and `btsnoop_hci.log` is the failed connection on the LG phone.

**Comment by dariuszseweryn** [comment]
If I will have a moment next week I will look into the logs to see if I can spot the problem.

**Comment by dariuszseweryn** [comment]
Closing due to inactivity. If new info will be available—feel free to reopen.

**Comment by ardmn** [comment]
Hello @dariuszseweryn. 
Sometimes I get similar problem  . Can you explene how read, understend logs ? I try useing Wireshark but not understen what's what.(about reading btsnoop_hci.log)

**Comment by dariuszseweryn** [comment]
Wireshark is reading the raw data that the BT controller sends. In this [article](https://medium.com/@urish/reverse-engineering-a-bluetooth-lightbulb-56580fcb7546) there is a part about using Wireshark which may be useful to you. You could check for the HCI log documentation on Google and/or Bluetooth 4.2 Spec.

**Comment by ardmn** [comment]
@dariuszseweryn Thank you! I will read it a little later :)

**Comment by ardmn** [comment]
Can I understend on what side problem with connection : android OS, my application, ble device ?
(I use sgs7 with android v6)

Log from application:
```
01-15 15:00:05.579 16648-16811/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:   QUEUED ConnectOperation(233924389)
01-15 15:00:05.579 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:  STARTED ConnectOperation(233924389)
01-15 15:00:05.599 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: connect() - device: 00:0B:57:1D:74:CB, auto: false
01-15 15:00:05.599 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: registerApp()
01-15 15:00:05.599 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: registerApp() - UUID=edf707ec-2e8b-40f8-9322-77ec81c860f5
01-15 15:00:05.639 16648-16662/com.ayrlabs.ayr.qa D/BluetoothGatt: onClientRegistered() - status=0 clientIf=9
01-15 15:00:10.679 16648-16662/com.ayrlabs.ayr.qa D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=9 device=00:0B:57:1D:74:CB
01-15 15:00:10.689 16648-16662/com.ayrlabs.ayr.qa D/RxBle#BluetoothGatt: onConnectionStateChange newState=0 status=133
01-15 15:00:10.699 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue: FINISHED ConnectOperation(233924389)
01-15 15:00:10.699 16648-16648/com.ayrlabs.ayr.qa W/System.err: com.polidea.rxandroidble.exceptions.BleDisconnectedException: Disconnected from 00:0B:57:1D:74:CB
01-15 15:00:10.699 16648-16811/com.ayrlabs.ayr.qa I/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (00:0B:57:1D:74:CB)
01-15 15:00:10.699 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:76)
01-15 15:00:10.699 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:228)
01-15 15:00:10.699 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
01-15 15:00:10.699 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.os.Binder.execTransact(Binder.java:453)
01-15 15:00:10.699 16648-16811/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:   QUEUED DisconnectOperation(59178154)
01-15 15:00:10.699 16648-16810/com.ayrlabs.ayr.qa D/RxBle#Executors$RunnableAdapter: Terminated.
01-15 15:00:10.699 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:  STARTED DisconnectOperation(59178154)
01-15 15:00:10.709 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: close()
01-15 15:00:10.709 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: unregisterApp() - mClientIf=9
01-15 15:00:10.719 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue: FINISHED DisconnectOperation(59178154)

01-15 15:00:28.059 16648-16811/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:   QUEUED ConnectOperation(192550922)
01-15 15:00:28.059 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:  STARTED ConnectOperation(192550922)
01-15 15:00:28.059 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: connect() - device: 00:0B:57:1D:74:CB, auto: false
01-15 15:00:28.059 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: registerApp()
01-15 15:00:28.059 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: registerApp() - UUID=8a58ac78-25eb-4288-8320-9bb9a70c2f66
01-15 15:00:28.109 16648-16662/com.ayrlabs.ayr.qa D/BluetoothGatt: onClientRegistered() - status=0 clientIf=9
01-15 15:00:33.159 16648-16662/com.ayrlabs.ayr.qa D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=9 device=00:0B:57:1D:74:CB
01-15 15:00:33.169 16648-16662/com.ayrlabs.ayr.qa D/RxBle#BluetoothGatt: onConnectionStateChange newState=0 status=133
01-15 15:00:33.169 16648-16648/com.ayrlabs.ayr.qa W/System.err: com.polidea.rxandroidble.exceptions.BleDisconnectedException: Disconnected from 00:0B:57:1D:74:CB
01-15 15:00:33.169 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:76)
01-15 15:00:33.169 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:228)
01-15 15:00:33.169 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
01-15 15:00:33.169 16648-16648/com.ayrlabs.ayr.qa W/System.err:     at android.os.Binder.execTransact(Binder.java:453)
01-15 15:00:33.169 16648-16662/com.ayrlabs.ayr.qa I/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (00:0B:57:1D:74:CB)
01-15 15:00:33.169 16648-16811/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:   QUEUED DisconnectOperation(49734735)
01-15 15:00:33.169 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue: FINISHED ConnectOperation(192550922)
01-15 15:00:33.169 16648-16810/com.ayrlabs.ayr.qa D/RxBle#Executors$RunnableAdapter: Terminated.
01-15 15:00:33.169 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue:  STARTED DisconnectOperation(49734735)
01-15 15:00:33.179 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: close()
01-15 15:00:33.179 16648-16812/com.ayrlabs.ayr.qa D/BluetoothGatt: unregisterApp() - mClientIf=9
01-15 15:00:33.189 16648-16666/com.ayrlabs.ayr.qa D/RxBle#ClientOperationQueue: FINISHED DisconnectOperation(49734735)
```
Image from Wireshark:
![log_img](https://user-images.githubusercontent.com/7188636/34986841-2832e48a-faca-11e7-9d78-d9115a708c9f.png)

[btsnoop_hci.zip - log file](https://github.com/Polidea/RxAndroidBle/files/1634890/btsnoop_hci.zip)

I see that from log in Wireshark that ble device create connection with android but in logs from application I see 'onConnectionStateChange newState=0 status=133' why it can happends ? And is this means that problem in Android ?

**Comment by dariuszseweryn** [comment]
I see in the logs that eventually you have connected. It looks like the problem is on the Android BLE stack side. You could try to reboot your device/bluetooth adapter and see if it happens again. Just remember that after this you should first scan your device before trying to connect with `autoConnect=false`

**Comment by ardmn** [comment]
@dariuszseweryn Thank you so much. Time to time this problem happens and it is really solver by ble device rebooting or smartphone rebooting . Why I need scan my device before trying to connect with it? Is it some workaround ?

**Comment by dariuszseweryn** [comment]
There is a bug in [resolving the address](https://stackoverflow.com/questions/43476369/android-save-ble-device-to-reconnect-after-app-close/43482099#43482099).

**Comment by ardmn** [comment]
Thanks . @dariuszseweryn I think scaning on android it not good for user experience because we need enable location service . Еspecially if application need restore connection in background or after starting application :( But It is what it is
