### ISSUE TITLE
DeadSystemException  Add `onError` handling.

### ISSUE THREAD

**Issue by ardmn** [Polidea/RxAndroidBle#443]
Hello I got interesting crash  report :
``java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.``
https://developer.android.com/reference/kotlin/android/os/DeadSystemException

I inspected my code and didn't find subscricption without error handling. Can it happends from library ? Thanks. 

### Library version
`1.4.3`

#### Steps to reproduce actual result
Don't know

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
    at rx.internal.schedulers.ScheduledAction.run(Unknown Source)
    at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
Caused by: e.b.f: android.os.DeadSystemException
    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(Unknown Source)
                                                                       call
    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(Unknown Source)
                                                                       call
    at rx.internal.util.ActionSubscriber.onError(Unknown Source)
    at rx.observers.SafeSubscriber._onError(Unknown Source)
    at rx.observers.SafeSubscriber.onError(Unknown Source)
    at rx.internal.operators.NotificationLite.next(Unknown Source)
                                           completed
                                           error
                                           accept
    at rx.internal.operators.OperatorReplay$UnboundedReplayBuffer.next(Unknown Source)
                                                               error
                                                               replay
    at rx.internal.operators.OperatorReplay$InnerProducer.request(Unknown Source)
                                                       index
    at rx.Subscriber.add(Unknown Source)
                  request
                  setProducer
    at rx.Subscriber.add(Unknown Source)
                  request
                  setProducer
    at rx.internal.operators.OperatorReplay$7.call(Unknown Source)
                                           call
    at rx.internal.operators.OperatorReplay$7.call(Unknown Source)
                                           call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.Observable.error(Unknown Source)
                  merge
                  merge
                  zip
                  buffer
                  debounce
                  doOnNext
                  doOnSubscribe
                  filter
                  sample
                  subscribe
                  subscribeOn
                  window
                  window
    at rx.Observable.just(Unknown Source)
                  switchOnNext
                  cacheWithInitialCapacity
                  delay
                  doOnTerminate
                  flatMap
                  subscribe
                  timeout
                  unsubscribeOn
    at com.polidea.rxandroidble.internal.serialization.ConnectionOperationQueueImpl.queue(Unknown Source)
                                                                                 terminate
                                                                                 log
                                                                                 onConnectionSubscribed
                                                                                 access$000
    at com.polidea.rxandroidble.internal.connection.ConnectorImpl$1$3.call(Unknown Source)
    at rx.internal.operators.OperatorDoOnSubscribe.call(Unknown Source)
                                                call
    at rx.internal.operators.OperatorDoOnSubscribe.call(Unknown Source)
                                                call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(Unknown Source)
                                                                    call
                                                                    setProducer
    ... 5 more
Caused by: java.lang.RuntimeException: android.os.DeadSystemException
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1369)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1328)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:625)
    at com.polidea.rxandroidble.RxBleAdapterStateObservable$1.call(Unknown Source)
                                                           call
    at com.polidea.rxandroidble.RxBleAdapterStateObservable$1.call(Unknown Source)
                                                           call
    at rx.internal.operators.OnSubscribeCreate.call(Unknown Source)
                                            call
    at rx.internal.operators.OnSubscribeCreate.call(Unknown Source)
                                            call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(Unknown Source)
    at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(Unknown Source)
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(Unknown Source)
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(Unknown Source)
                                                                 fastPath
    at rx.Subscriber.add(Unknown Source)
                  request
                  setProducer
    at rx.internal.operators.OnSubscribeFromArray.call(Unknown Source)
                                               call
    at rx.internal.operators.OnSubscribeFromArray.call(Unknown Source)
                                               call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeConcatMap.call(Unknown Source)
                                               call
    at rx.internal.operators.OnSubscribeConcatMap.call(Unknown Source)
                                               call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeFilter.call(Unknown Source)
                                            call
    at rx.internal.operators.OnSubscribeFilter.call(Unknown Source)
                                            call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(Unknown Source)
                                                        onError
                                                        addInner
                                                        tryEmit
                                                        emitScalar
                                                        emitScalar
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(Unknown Source)
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(Unknown Source)
                                                                 fastPath
    at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(Unknown Source)
                                                                 fastPath
    at rx.Subscriber.add(Unknown Source)
                  request
                  setProducer
    at rx.internal.operators.OnSubscribeFromArray.call(Unknown Source)
                                               call
    at rx.internal.operators.OnSubscribeFromArray.call(Unknown Source)
                                               call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OperatorReplay.connect(Unknown Source)
    at rx.observables.ConnectableObservable.refCount(Unknown Source)
                                         autoConnect
                                         autoConnect
    at rx.observables.ConnectableObservable.refCount(Unknown Source)
                                         autoConnect
                                         autoConnect
    at com.polidea.rxandroidble.internal.connection.DisconnectionRouter.<init>(Unknown Source)
    at com.polidea.rxandroidble.internal.connection.DisconnectionRouter_Factory.get(Unknown Source)
                                                                             create
    at com.polidea.rxandroidble.internal.connection.DisconnectionRouter_Factory.get(Unknown Source)
    at dagger.internal.DoubleCheck.get(Unknown Source)
    at com.polidea.rxandroidble.internal.connection.RxBleGattCallback_Factory.get(Unknown Source)
                                                                           create
    at com.polidea.rxandroidble.internal.connection.RxBleGattCallback_Factory.get(Unknown Source)
    at dagger.internal.DoubleCheck.get(Unknown Source)
    at com.polidea.rxandroidble.internal.operations.ConnectOperation_Factory.get(Unknown Source)
                                                                          create
    at com.polidea.rxandroidble.internal.operations.ConnectOperation_Factory.get(Unknown Source)
    at com.polidea.rxandroidble.DaggerClientComponent$DeviceComponentImpl$ConnectionComponentImpl.initialize(Unknown Source)
                                                                                               connectOperation
    at com.polidea.rxandroidble.internal.connection.ConnectorImpl$1.call(Unknown Source)
    at com.polidea.rxandroidble.internal.connection.ConnectorImpl$1.call(Unknown Source)
    at rx.internal.operators.OnSubscribeDefer.call(Unknown Source)
                                           call
    at rx.internal.operators.OnSubscribeDefer.call(Unknown Source)
                                           call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeDefer.call(Unknown Source)
                                           call
    at rx.internal.operators.OnSubscribeDefer.call(Unknown Source)
                                           call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.internal.operators.OnSubscribeMap.call(Unknown Source)
                                         call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OperatorReplay.connect(Unknown Source)
    at rx.internal.operators.OnSubscribeRefCount.call(Unknown Source)
                                              onSubscribe
                                              doSubscribe
                                              disconnect
                                              call
                                              access$000
    at rx.internal.operators.OnSubscribeRefCount.call(Unknown Source)
                                              onSubscribe
                                              doSubscribe
                                              disconnect
                                              call
                                              access$000
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.internal.operators.OnSubscribeLift.call(Unknown Source)
                                          call
    at rx.Observable.create(Unknown Source)
                  unsafeCreate
                  lift
                  compose
                  combineLatest
                  combineLatest
                  concat
                  concat
                  defer
                  from
                  from
                  fromCallable
                  interval
                  just
                  merge
                  merge
                  timer
                  buffer
                  collect
                  concatMap
                  delay
                  doOnCompleted
                  doOnError
                  flatMapSingle
                  observeOn
                  observeOn
                  observeOn
                  reduce
                  subscribe
                  subscribe
                  unsafeSubscribe
                  subscribe
                  subscribeOn
                  timeout
                  window
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(Unknown Source)
                                                                    call
                                                                    setProducer
    at rx.android.schedulers.LooperScheduler$ScheduledAction.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6692)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: android.os.DeadSystemException
    ... 84 more
```

**Comment by dariuszseweryn** [comment]
Hello @ardmn 

I have looked thought the `master-rxjava1` branch for every `.subscribe()` statements. Most of them are only passing the `onError()` to the observers/emitters. Otherwise they either have `onError()` handling or are subscribed to `Observable`'s that are not able to emit errors.

It seems very unlikely that this is caused by the library.

**Comment by dariuszseweryn** [comment]
Btw. the newest `RxJava1` library version is `1.5.0`

**Comment by dariuszseweryn** [comment]
Revisiting — I still have no idea what has happened. I have no scenario for reproduction and I do not see other reports about this issue. It seems to be a marginal problem and I do not have time to investigate it further. Closing for now.

Feel free to add more info when available or when other reports will be available
