### ISSUE TITLE
SecurityException when starting a scan with PendingIntent

### ISSUE THREAD

**Issue by dariuszseweryn** [Polidea/RxAndroidBle#491]
When calling `BackgroundScanner.scanBleDeviceInBackground()` the below error may be thrown:

```
java.lang.SecurityException: Need BLUETOOTH_PRIVILEGED permission: Neither user 10188 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScanForIntent(IBluetoothGatt.java:977)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:249)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:166)
        at com.polidea.rxandroidble2.internal.util.RxBleAdapterWrapper.startLeScan(RxBleAdapterWrapper.java:57)
        at com.polidea.rxandroidble2.internal.scan.BackgroundScannerImpl.scanBleDeviceInBackground(BackgroundScannerImpl.java:56)
```

It seems that [the Android OS for certain settings needs `BLUETOOTH_PRIVILIGED` permission](https://android.googlesource.com/platform/packages/apps/Bluetooth/+/android-8.0.0_r1/src/com/android/bluetooth/gatt/GattService.java#2508)

Thread for discussion

_Originally posted by @gryffindor14 in https://github.com/Polidea/RxAndroidBle/issues/481#issuecomment-424480631_

**Comment by dariuszseweryn** [comment]
This ticket is invalid [as this situation to happen needs a use of `SystemApi`](https://android.googlesource.com/platform/frameworks/base.git/+/android-8.0.0_r1/core/java/android/bluetooth/le/ScanSettings.java#124) or calling the API when the Bluetooth is not on [which was fixed recently](#487)
