### ISSUE TITLE
com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='C4:A6:E6:DD:30:9A' with status 133 (GATT_ERROR)

### ISSUE THREAD

**Issue by denghewenai** [Polidea/RxAndroidBle#606]
### Disclaimer
Before you will post a new issue to the RxAndroidBle library consider if you are filling a bug/feature request or a general question 
about:
* Usage of RxJava
* Usage of Bluetooth Low Energy
* Usage of RxAndroidBle
* Weird behaviour of the peripheral you are using
* Other not directly related to a new feature request or a bug

If any of the above points seems to match your use case — consider using Google or creating a question on www.stackoverflow.com with 
a tag `rxandroidble` where it will be easier to access by other people with similar questions. Issues that are not bugs or feature requests
will be closed.

### Library version
`1.10.1`

#### Steps to reproduce actual result
<br />1.establishConnection
<br />2.Turn off Bluetooth in settings
<br />3.Turn on Bluetooth in settings
<br />4.establishConnection

#### Actual result
// BleDisconnectedException
I killed the application's process and re-opened it will still get this exception.When the connection fails, I call the method of scanning the device in the following code and then connect, I can connect successfully.
#### Expected result
// connection succeeded

#### Minimum code snippet reproducing the issue
    private fun prepareConnectionObservable(): Observable<RxBleConnection> =
        bleDevice.establishConnection(false)
            .takeUntil(disconnectTriggerSubject)
            .compose(ReplayingShare.instance())

    private fun connectGatt() {
        connectionObservable.observeOn(AndroidSchedulers.mainThread())
            .subscribe({ onConnectionReceived() }, { onConnectionFailure(it) })
            .let { connectionDisposables.add(it) }
    }

    fun scanBleDevices(): Observable<ScanResult> {
        val scanSettings = ScanSettings.Builder()
            .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
            .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
            .build()

        val scanFilter = ScanFilter.Builder()
            .setServiceUuid(ParcelUuid.fromString(SERVICE_ADVERTISING_UUID))
            .build()
        Log.i(TAG, "uuid" + scanFilter.serviceUuid)

        return rxBleClient.scanBleDevices(scanSettings,scanFilter)
    }

#### Logs from the application running with settings:
```java
RxBleClient.updateLogOptions(new LogOptions.Builder()
        .setLogLevel(LogConstants.DEBUG)
        .setMacAddressLogSetting(LogConstants.MAC_ADDRESS_FULL)
        .setUuidsLogSetting(LogConstants.UUIDS_FULL)
        .setShouldLogAttributeValues(true)
        .build()
);
```

```
// paste logs here
```
2019-09-04 14:50:14.087 16899-16899/com.cvte.maxhub.columnloudspeaker I/RxBle#LoadedApk: Adapter state changed: STATE_TURNING_OFF
2019-09-04 14:50:14.106 16899-16899/com.cvte.maxhub.columnloudspeaker D/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (MAC='C4:A6:E6:DD:30:9A')
    com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='C4:A6:E6:DD:30:9A' with status -1 (UNKNOWN)
        at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:53)
        at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:50)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onNext(ObservableRefCount.java:207)
        at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.onNext(ObservablePublishAlt.java:177)
        at io.reactivex.internal.operators.observable.ObservableUnsubscribeOn$UnsubscribeObserver.onNext(ObservableUnsubscribeOn.java:60)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
        at com.polidea.rxandroidble2.RxBleAdapterStateObservable$1$1.onReceive(RxBleAdapterStateObservable.java:67)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1419)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6865)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.polidea.rxandroidble2.exceptions.BleAdapterDisabledException
        at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:53) 
        at com.polidea.rxandroidble2.internal.connection.DisconnectionRouter$3.apply(DisconnectionRouter.java:50) 
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57) 
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52) 
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506) 
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62) 
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onNext(ObservableRefCount.java:207) 
        at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.onNext(ObservablePublishAlt.java:177) 
        at io.reactivex.internal.operators.observable.ObservableUnsubscribeOn$UnsubscribeObserver.onNext(ObservableUnsubscribeOn.java:60) 
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58) 
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66) 
        at com.polidea.rxandroidble2.RxBleAdapterStateObservable$1$1.onReceive(RxBleAdapterStateObservable.java:67) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1419) 
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6865) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-09-04 14:50:14.121 16899-16899/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: QUEUED   DisconnectOperation(98612040)
2019-09-04 14:50:14.125 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: STARTED  DisconnectOperation(98612040)
2019-09-04 14:50:14.128 16899-16944/com.cvte.maxhub.columnloudspeaker I/RxBle#ClientOperationQueue: RUNNING  DisconnectOperation{MAC='C4:A6:E6:DD:30:9A'}
2019-09-04 14:50:14.139 16899-16899/com.cvte.maxhub.columnloudspeaker W/System.err:     at com.polidea.rxandroidble2.RxBleAdapterStateObservable$1$1.onReceive(RxBleAdapterStateObservable.java:67)
2019-09-04 14:50:14.175 16899-16916/com.cvte.maxhub.columnloudspeaker I/RxBle#GattCallback: MAC='C4:A6:E6:DD:30:9A'  onConnectionStateChange(), status=0, value=0
2019-09-04 14:50:14.192 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: FINISHED DisconnectOperation(98612040) in 69 ms
2019-09-04 14:50:14.374 16899-16899/com.cvte.maxhub.columnloudspeaker D/RxBle#Client: Received new options (LogOptions{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=null, logger=null}) and merged with old setup: LoggerSetup{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=true, logger=com.polidea.rxandroidble2.internal.RxBleLog$1@bced8de}. New setup: LoggerSetup{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=true, logger=com.polidea.rxandroidble2.internal.RxBleLog$1@bced8de}
2019-09-04 14:50:19.153 16899-16899/com.cvte.maxhub.columnloudspeaker D/RxBle#Client: Received new options (LogOptions{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=null, logger=null}) and merged with old setup: LoggerSetup{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=true, logger=com.polidea.rxandroidble2.internal.RxBleLog$1@bced8de}. New setup: LoggerSetup{logLevel=3, macAddressLogSetting=2, uuidLogSetting=2, shouldLogAttributeValues=true, shouldLogScannedPeripherals=true, logger=com.polidea.rxandroidble2.internal.RxBleLog$1@bced8de}
2019-09-04 14:50:19.674 16899-16952/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: QUEUED   ConnectOperation(25502718)
2019-09-04 14:50:19.676 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: STARTED  ConnectOperation(25502718)
2019-09-04 14:50:19.678 16899-16944/com.cvte.maxhub.columnloudspeaker I/RxBle#ClientOperationQueue: RUNNING  ConnectOperation{MAC='C4:A6:E6:DD:30:9A', autoConnect=false}
2019-09-04 14:50:49.697 16899-16916/com.cvte.maxhub.columnloudspeaker I/RxBle#GattCallback: MAC='C4:A6:E6:DD:30:9A'  onConnectionStateChange(), status=133, value=0
2019-09-04 14:50:49.703 16899-16916/com.cvte.maxhub.columnloudspeaker D/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (MAC='C4:A6:E6:DD:30:9A')
    com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='C4:A6:E6:DD:30:9A' with status 133 (GATT_ERROR)
        at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:80)
        at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:262)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:770)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:39)
        at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:257)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:71)
        at android.os.Binder.execTransact(Binder.java:756)
2019-09-04 14:50:49.712 16899-16916/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: QUEUED   DisconnectOperation(60498549)
2019-09-04 14:50:49.714 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: FINISHED ConnectOperation(25502718) in 30037 ms
2019-09-04 14:50:49.716 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: STARTED  DisconnectOperation(60498549)
2019-09-04 14:50:49.718 16899-16944/com.cvte.maxhub.columnloudspeaker I/RxBle#ClientOperationQueue: RUNNING  DisconnectOperation{MAC='C4:A6:E6:DD:30:9A'}
2019-09-04 14:50:49.730 16899-16944/com.cvte.maxhub.columnloudspeaker D/RxBle#ClientOperationQueue: FINISHED DisconnectOperation(60498549) in 13 ms

**Comment by dariuszseweryn** [comment]
[Known Android issue](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-Cannot-connect#connect-without-a-scan)
